---
title: "Explore Pipeline Results"
author: "Eric Bridgeford"
date: "July 25, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
require(ggplot2)
require(scales)
require(lme4)
require(reshape2)
require(plyr)
require(dplyr)
library(tidyr)
require(ggbeeswarm)
require(latex2exp)
require(ggpubr)
require(grid)
require(gridExtra)
require(stringr)
require(data.table)
require(abind)
require(tidyverse)
```


```{r}
results <- readRDS('./data/real/full_results_pipeline.rds')

single.ds <- lapply(results, function(res) {
  res %>%
    subset(Dataset == "BNU1")
  })

```

# Statistic vs Performance

Statistic on the graphs, vs. MGC/Dcorr for age (regression) and sex (classification) task on the graphs embedded using the strategy indicated

```{r}
stat.vs.perf <- merge(results$stat, results$prob, by=c("Reg", "FF", "Scr", "GSR", "Parcellation", "xfm", "Dataset"))

do.call(rbind, lapply(unique(stat.vs.perf$xfm), function(xf) {
  do.call(rbind, lapply(unique(stat.vs.perf$alg), function(al) {
    do.call(rbind, lapply(unique(stat.vs.perf$Dataset), function(ds) {
      do.call(rbind, lapply(unique(stat.vs.perf$task), function(ta) {
        do.call(rbind, lapply(unique(stat.vs.perf$embed), function(em) {
          res.ds.al.ta.em <- stat.vs.perf %>%
            filter(alg == as.character(al) & Dataset == as.character(ds) & 
                     task == as.character(ta) & embed == as.character(em) & xfm == as.character(xf))
          reg.fit <- lm(stat.y ~ stat.x, data=res.ds.al.ta.em)
          return(data.frame(Dataset=ds, alg=al, task=ta, xfm=xf, embed=em, slope=reg.fit$coefficients["stat.x"],
                            intercept=reg.fit$coefficients["(Intercept)"]))
        }))
      }))
    })) %>%
      ggplot() +
        geom_abline(aes(slope=slope, intercept=intercept, group=Dataset)) +
        facet_grid(task ~ embed, scales="free_y") +
        theme_bw()
  }))
}))
  
```


# Statistic vs MGC/Dcorr

Statistic on the graphs, vs. MGC/Dcorr for age (regression) and sex (classification) task on the graphs

```{r}
stat.vs.perf <- merge(results$stat, results$dcor, by=c("Reg", "FF", "Scr", "GSR", "Parcellation", "xfm", "Dataset")) %>%
  filter(method == "mgc")

alg.titles <- c("Discriminability", "ANOVA", "ICC", "I2C2")
fig.labs <- c("(A)", "(B)", "(C)", "(D)")

dset.cols <- readRDS("./dset_colors.rds")
lapply(unique(stat.vs.perf$xfm), function(xf) {
  do.call(grid.arrange, lapply(1:length(unique(stat.vs.perf$alg)), function(i) {
    al <- unique(stat.vs.perf$alg)[i]
    do.call(rbind, lapply(unique(stat.vs.perf$task), function(ta) {
      dat.task <- do.call(rbind, lapply(unique(stat.vs.perf$Dataset), function(ds) {
        do.call(rbind, lapply(unique(stat.vs.perf$method), function(meth) {
          res.ds.al.ta.meth <- stat.vs.perf %>%
            filter(alg == as.character(al) & Dataset == as.character(ds) & 
                     task == as.character(ta) & method == as.character(meth) & xfm == as.character(xf))
          reg.fit <- lm(stat.y ~ stat.x, data=res.ds.al.ta.meth)
          sum.fit <- summary(reg.fit)
          pval.test <- pt(coef(sum.fit)[2,3], sum.fit$df[2], lower.tail=FALSE)
          return(data.frame(Dataset=ds, alg=al, task=ta, xfm=xf, method=meth, slope=reg.fit$coefficients["stat.x"],
                            intercept=reg.fit$coefficients["(Intercept)"], pval=pval.test))
        }))
      }))
      sl.mean <- mean(dat.task$slope); pval.med <- median(dat.task$pval)
      dat.task$task <- sprintf("%s, Mean(Slope)=%.3f, Med(pval)=%.3f", ta, sl.mean, pval.med)
      return(dat.task)
    })) %>%
      ggplot() +
        geom_abline(aes(slope=slope, intercept=intercept, color=Dataset, group=Dataset)) +
        facet_grid(. ~ task, scales="free_y") +
        theme_bw() +
        ggtitle(sprintf("%s %s", fig.labs[i], alg.titles[i])) +
        xlab(alg.titles[i]) +
        ylab("Test Statistic") +
        scale_color_manual(values=dset.cols) +
        guides(color=FALSE)
  }))
})
```
