---
title: "Figure 5"
author: "Eric Bridgeford"
date: "February 28, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
require(ggplot2)
require(scales)
require(lme4)
require(reshape2)
require(dplyr)
library(tidyr)
require(ggbeeswarm)
require(latex2exp)
require(ggExtra)
require(ggpubr)
require(grid)
require(gridExtra)
require(stringr)
require(data.table)
```


```{r}
fmri.results <- readRDS('./data/real/discr_fmri_results.rds')
```

# fMRI Multiplot

```{r}
reg_opts <- c("A", "F")
names(reg_opts) <- c("ANTs", "FSL")
freq_opts <- c("F", "N")
names(freq_opts) <- c(TRUE, FALSE)
scrub_opts <- c("S", "X")
names(scrub_opts) <- c(TRUE, FALSE)
gsr_opts <- c("G", "X")
names(gsr_opts) <- c(TRUE, FALSE)
atlas_opts <- c("A", "C", "D", "H")
names(atlas_opts) <- c("AAL", "CC200", "Desikan", "HO")
dsets <- unique(fmri.results$Dataset)

fmri.results <- do.call(rbind, lapply(1:dim(fmri.results)[1], function(i) {
  dat <- fmri.results[i,]
  name <- paste(reg_opts[as.character(dat$Reg)], 
                freq_opts[abs(as.numeric(dat$FF) - 1) + 1],
                scrub_opts[abs(as.numeric(dat$Scr) - 1) + 1],
                gsr_opts[abs(as.numeric(dat$GSR) - 1) + 1],
                atlas_opts[as.character(dat$Parcellation)], sep="")
  return(cbind(data.frame(Name=name), dat))
}))
```

```{r}
nan.mean <- function(x) {
  mean(x, na.rm=TRUE)
}
fmri.summarized <- aggregate(list(me.discr=fmri.results$discr), 
                             by=list(Name=fmri.results$Name), FUN=nan.mean)
fmri.results$Name <- factor(fmri.results$Name, 
                                levels=as.character(fmri.summarized$Name[order(fmri.summarized$me.discr, decreasing = TRUE)]),
                                ordered=TRUE)
```

```{r, fig.height=8, fig.width=12}
ggplot(fmri.results, aes(x=Name, y=discr, color=Dataset, size=nscans)) +
  geom_point() +
  xlab("Preprocessing Strategy") +
  ylab("Discriminability") +
  theme_bw() +
  ggtitle("Comparing Discriminability Across 64 Preprocessing Strategies") +
  theme(axis.text.x=element_text(angle=90)) +
  scale_size_continuous(name="#Scans") +
  stat_summary(fun.y="mean", color="black", geom="point", shape="triangle", size=2) +
  guides(color=guide_legend(ncol=2))
```

```{r}
# Registration
reg.sum <- aggregate(list(discr=fmri.results$discr), 
                     by=list(Dataset=fmri.results$Dataset, FF=fmri.results$FF,
                             Scr=fmri.results$Scr, GSR=fmri.results$GSR,
                             Parcellation=fmri.results$Parcellation), FUN=function(x) {NaN})
reg.result <- do.call(rbind, lapply(1:dim(reg.sum)[1], function(i) {
  rows <- subset(fmri.results, Dataset==reg.sum$Dataset[i] & FF==reg.sum$FF[i] & Scr==reg.sum$Scr[i] &
                   GSR==reg.sum$GSR[i] & Parcellation==reg.sum$Parcellation[i])
  reslt <- reg.sum[i,]
  if (dim(rows)[1] > 1) {
    reslt$discr <- rows$discr[rows$Reg == "FSL"] - rows$discr[rows$Reg == "ANTs"]
  } else {
    print()
  }
  return(reslt)
}))

# Freq Filtering
freq.sum <- aggregate(list(discr=fmri.results$discr), 
                     by=list(Dataset=fmri.results$Dataset, Reg=fmri.results$Reg,
                             Scr=fmri.results$Scr, GSR=fmri.results$GSR,
                             Parcellation=fmri.results$Parcellation), FUN=function(x) {NaN})
freq.result <- do.call(rbind, lapply(1:dim(freq.sum)[1], function(i) {
  rows <- subset(fmri.results, Dataset==freq.sum$Dataset[i] & Reg==freq.sum$Reg[i] & Scr==freq.sum$Scr[i] &
                   GSR==freq.sum$GSR[i] & Parcellation==freq.sum$Parcellation[i])
  reslt <- reg.sum[i,]
  if (dim(rows)[1] > 1) {
    reslt$discr <- rows$discr[rows$FF == FALSE] - rows$discr[rows$FF == TRUE]
  } else {
    print()
  }
  return(reslt)
}))


# Scrubbing
scr.sum <- aggregate(list(discr=fmri.results$discr), 
                     by=list(Dataset=fmri.results$Dataset, Reg=fmri.results$Reg,
                             FF=fmri.results$FF, GSR=fmri.results$GSR,
                             Parcellation=fmri.results$Parcellation), FUN=function(x) {NaN})
scr.result <- do.call(rbind, lapply(1:dim(scr.sum)[1], function(i) {
  rows <- subset(fmri.results, Dataset==scr.sum$Dataset[i] & Reg==scr.sum$Reg[i] & FF==scr.sum$FF[i] &
                   GSR==scr.sum$GSR[i] & Parcellation==scr.sum$Parcellation[i])
  reslt <- reg.sum[i,]
  if (dim(rows)[1] > 1) {
    reslt$discr <- rows$discr[rows$Scr == FALSE] - rows$discr[rows$Scr == TRUE]
  } else {
    print()
  }
  return(reslt)
}))

# Scrubbing
gsr.sum <- aggregate(list(discr=fmri.results$discr), 
                     by=list(Dataset=fmri.results$Dataset, Reg=fmri.results$Reg,
                             FF=fmri.results$FF, Scr=fmri.results$Scr,
                             Parcellation=fmri.results$Parcellation), FUN=function(x) {NaN})
gsr.result <- do.call(rbind, lapply(1:dim(gsr.sum)[1], function(i) {
  rows <- subset(fmri.results, Dataset==gsr.sum$Dataset[i] & Reg==gsr.sum$Reg[i] & FF==gsr.sum$FF[i] &
                   Scr==gsr.sum$Scr[i] & Parcellation==gsr.sum$Parcellation[i])
  reslt <- gsr.sum[i,]
  if (dim(rows)[1] > 1) {
    reslt$discr <- rows$discr[rows$GSR == TRUE] - rows$discr[rows$GSR == FALSE]
  } else {
    print("")
  }
  return(reslt)
}))


# Parcellation
parcel.sum <- aggregate(list(discr=fmri.results$discr), 
                     by=list(Dataset=fmri.results$Dataset, Reg=fmri.results$Reg,
                             FF=fmri.results$FF, Scr=fmri.results$Scr,
                             GSR=fmri.results$GSR), FUN=function(x) {NaN})
parcel.result <- do.call(rbind, lapply(1:dim(parcel.sum)[1], function(i) {
  rows <- subset(fmri.results, Dataset==parcel.sum$Dataset[i] & Reg==parcel.sum$Reg[i] & FF==parcel.sum$FF[i] &
                   Scr==parcel.sum$Scr[i] & GSR==parcel.sum$GSR[i])
  reslt <- parcel.sum[i,]
  if (dim(rows)[1] > 1) {
    reslt$discr <- rows$discr[rows$Parcellation == "CC200"] - max(rows$discr[rows$Parcellation != "CC200"])
  } else {
    print("")
  }
  return(reslt)
}))

result <- rbind(data.frame(discr=reg.result$discr, Option="FSL - ANTs"), 
                data.frame(discr=freq.result$discr, Option="FF - NFF"), 
                data.frame(discr=scr.result$discr, Option="SCR - NSC"), 
                data.frame(discr=gsr.result$discr, Option="GSR - NGS"), 
                data.frame(discr=parcel.result$discr, Option="CC200 - max(others)"))
```

```{r}
ggplot(result, aes(x=Option, y=discr, color=Option)) +
  geom_jitter(alpha=0.8, size=0.6) +
  geom_violin(color="black", aes(fill=Option)) +
  theme_bw() +
  xlab("") +
  ylab(TeX("$\\hat{D}_{best} - max(\\hat{D}_{others})$")) +
  ggtitle("Impact of Preprocessing Choice on Discriminability") +
  theme_bw()
```