---
title: "Simulations"
author: "Eric"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r}
require(mgc)
require(ggplot2)
n=400
d=1
```

```{r}
plot_sim <- function(X, Y, name) {
  if (!is.null(dim(Y))) {
    Y <- Y[, 1]
  }
  data <- data.frame(x1=X[,1], y=Y)
  ggplot(data, aes(x=x1, y=y)) +
    geom_point() +
    xlab("x") +
    ylab("y") +
    ggtitle(name)
}
```

In this notebook, we will review the simulation algorithms provided in the `mgc` paper. All simulations will be `n=400` examples in `d=2` dimensions.

# Linear

```{r}
data <- mgc.sims.linear(n, d)
X <- data$X; Y <- data$Y
plot_sim(X, Y, "Linear Simulation")
```

# Exponential

```{r}
data <- mgc.sims.exp(n, d)
X <- data$X; Y <- data$Y
plot_sim(X, Y, "Exponential Simulation")
```

# Cubic

```{r}
data <- mgc.sims.cubic(n, d)
X <- data$X; Y <- data$Y
plot_sim(X, Y, "Cubic Simulation")
```

# Joint-Normal

```{r}
data <- mgc.sims.joint(n, d)
X <- data$X; Y <- data$Y
plot_sim(X, Y, "Joint-Normal Simulation")
```
# Step

```{r}
data <- mgc.sims.step(n, d)
X <- data$X; Y <- data$Y
plot_sim(X, Y, "Step-Fn Simulation")
```

# Quadratic

```{r}
data <- mgc.sims.quad(n, d)
X <- data$X; Y <- data$Y
plot_sim(X, Y, "Quadratic Simulation")
```

# W-Shape

```{r}
data <- mgc.sims.wshape(n, d)
X <- data$X; Y <- data$Y
plot_sim(X, Y, "W Simulation")
```

# Spiral

```{r}
data <- mgc.sims.spiral(n, d)
X <- data$X; Y <- data$Y
plot_sim(X, Y, "Spiral Simulation")
```
# Uncorrelated Bernoulli

```{r}
data <- mgc.sims.ubern(n, d)
X <- data$X; Y <- data$Y
plot_sim(X, Y, "Uncorrelated Bernoulli Simulation")
```
